image: registry.gitlab.inria.fr/nixos-compose/nixos-compose:doc
pages:
  script:
    - mdbook build -d public
  artifacts:
    paths:
      - public
  tags:
      - ci.inria.fr
      - small  
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
