image: registry.gitlab.inria.fr/nixos-compose/nixos-compose:doc
pages:
  script:
    - mkdir -p public
    - mdbook build docs -d ../public
  artifacts:
    paths:
      - public
  tags:
      - ci.inria.fr
      - small
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
